# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
name: phot_class

channels:
  - conda-forge

dependencies:
  - python=3.7.4
  - nb_conda_kernels
  - pip=19.1.1
  - astropy=3.2.1
  - bokeh=1.3.4
  - matplotlib=3.1.1
  - pandas=0.25.1
  - requests=2.22.0
  - scipy=1.3.1
  - sncosmo=2.0.0

  - pip:
      - nestle==0.2.0
      - sndata==0.7.0
      - emcee==2.2.1
      - pyyaml==5.1.2
      - tqdm==4.35.0
      - sklearn
      - sphinx-rtd-theme==0.4.3
      - numpy==1.17.2
      - iminuit==1.3.7
      - nestle==0.2.0
      - pytest-cov
      - python-coveralls

      # For test running
      - pytest==5.1.2
      - coverage==4.5.4

      # For documentation building
      - sphinx==2.2.0
      - sphinx-argparse==0.2.5
      - sphinx-rtd-theme==0.4.3
